# GLOBAL SITE SETTINGS

# General
seo_title: "Enterprise Wide Australia"
title: Enterprise Wide
company: Enterprise Wide
description: ""

# Contact Info
email: info@enterprisewide.com.au
phone: (05) 555 555 555
fax: (05) 555 555
address: "366 Jefferson Court Hendersonville, NC 28792"

# Social Networks
facebook:
linked_in:
google_plus:

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"